services:
  accounts:
    image: "mohitshaw01/accounts:v1"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          memory: "500m"
          cpus: "0.5"
    networks:
      - eazybytes
  cards:
    image: "mohitshaw01/cards:v1"
    container_name: "cards_ms"
    ports:
      - "9000:9000"
    restart: always
    deploy:
      resources:
        limits:
          memory: "500m"
          cpus: "0.5"
    networks:
      - eazybytes

networks:
  eazybytes:
    driver: "bridge"