server:
  port:8080
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "1.0"

account:
  message : "welcome to account service"
  contact:
    - email: "8M5lG@example.com"
    - phone: "1234567890"
  address:
    street: "street"
    city: "city"
    state: "state"
    zip: "12345"
  onCallSupport :
    - email: "8M5lG@example.com"
    - phone: "1234567890"